/**
 * 
 */
package io.github.azanx.shopping_list.domain;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Test;

/**
 * @author Kamil Piwowarski
 *
 */
//Unit Tests for AppUser domain class, leaving out tests for autogenerated methods (like getters and setters)
public class AppUserTest {

	private AppUser appUser;
	
	@Before
	public void setup() {
		appUser = new AppUser("Test_user", "secret", "test@test.com");
	}
	
	@Test
	public void addList() {
		String listName = "Test list";
		assertEquals(listName, appUser.addShoppingList("Test list").getListName());
	}

	@Test public void removeList() {
		//TODO implement
	}
}
