/**
 * 
 */
package io.github.azanx.shopping_list.domain;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.junit.Before;
import org.junit.Test;

/**
 * @author Kamil Piwowarski
 *
 */
//Unit Tests for AppUser domain class, leaving out tests for autogenerated methods (like getters and setters)
public class AppUserTest {

    private AppUser user;

    @Before
    public void setup() {
        user = new AppUser("Test_user", "secret", "test@test.com");
        user.setId(1L); // we have to set id manually as we are not writing to database!
    }

    @Test
    public void addList() {
        String listName = "Test list";
        ShoppingList newList = user.addShoppingList("Test list");
        assertNotNull(newList);
        assertEquals(listName, newList.getListName());
    }
}
